layout: stacked #sidebar # stacked #sidebar
style: light #dark  #light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name
    - repo-HTML

social_media:
  # behance: your_username
  # dribbble: your_username
    facebook: millojsg
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
    twitter: millojsg1
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: github
    web_url: https://github.com/
    image_url: https://github.githubassets.com/images/modules/logos_page/Octocat.png

  - name: msdn
    web_url: https://docs.microsoft.com/es-es/visualstudio/get-started/visual-basic/?view=vs-2019
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/439px-Microsoft_logo.svg.png

  - name: w3schools
    web_url: https://www.w3schools.com/
    image_url: https://lh3.googleusercontent.com/i-ij7KM2pFUUpFE31QAUDXg5mzGFNbm16S4tjmg2ZyuhCGLgNJ8oXJRbq7ysh6LoZg=s180-rw

  - name: RigZone
    web_url: https://www.rigzone.com/a-sql-jobs/?page=2
    image_url: https://media-exp1.licdn.com/dms/image/C560BAQGgmY8xZU2GGg/company-logo_200_200/0?e=2159024400&v=beta&t=rYxxxIgoen5gia7kMwm9z2qWqB_2IMXsfZFghAxfe18

  - name: Luis Dueñas Blog
    web_url: http://lduenash.blogspot.com/
    image_url: https://steamuserimages-a.akamaihd.net/ugc/922541006440575185/25EBBFBD6D71F6A2C146D7C2E37EB7FC919184D5/

  - name: HackerRank
    web_url: https://www.hackerrank.com/
    image_url: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxISEhMSEhASEBIXEBMYGBUQDQ8VEhAXFRcXGBoXExUYHSgiGBolGxYVIjEjJikrLi4uFx8zOD8sNyguLi0BCgoKDg0OGhAQGysiHx8tNy0wKy4tLS0rLS0tMC0tLS0tLS0tLS8vLS0tLS0tLSstLS0tLS0tKy0tKy0rLS0tLf/AABEIAMgAyAMBEQACEQEDEQH/xAAbAAEAAgMBAQAAAAAAAAAAAAAABgcBAgUDBP/EAD8QAAIBAgIECQkIAQUBAAAAAAABAgMRBAYFEiFRBxMxMkFhcXKxIiM0UnOBkcHRFVRigpKhsuGiJEJjg9IU/8QAGgEBAAIDAQAAAAAAAAAAAAAAAAQFAQMGAv/EAC0RAQACAQIDBQgDAQAAAAAAAAABAgMEEQUhMTIzQVFxEiJCYYGRodETFFIk/9oADAMBAAIRAxEAPwC8QAAAAAAAAAABytKZgoULqU9afqw2v37jXbLWqJn1uLDymd58oRHSeba1S6h5mP4dsn2y+hHtmtPTkps/E8t+Vfdj8uFx8762vLW36zv8TTvKB7dt99+bvaMzbWp2VTz0fxbJLsl9TdXNaOvNPwcTy05W96Pylui8wUK9lGerP1Z7H7t5IrlrZc4NbizconafKXVNiWAAAAAAAAAAAAAAAAAAABytLZgo0Nkpa0/Uhtfv3Gu+WtUTUa3Fh5TO8+UIZpXNFetdJ8VDdB7X2yI181rKPUcQy5eUco+Th3NSCGGAMgYLmWXc0VmivRsm+Nhum9q7JG2ma1U7T8Qy4uU84+aZ6JzBRr7Iy1Z+pPY/dvJNMtbLzT63Fm5RO0+UuqbEsAAAAAAAAAAAAAAA+LSWlKVCN6k0t0VtlLsR5teK9WjNqMeGN7yhOmM2Vat40/Mw6n5cu19HuIt80z0Ueo4lkycqco/KPNmhWsAAAAAAAAZTAkOh82VaVo1PPQ635a7H0+830zTHVZafiWTHyvzj8pto3SlKvG9Oae+L2Sj2olVvFui8w6jHmjekvtPTeAAAAAAAAAAGlWoopyk1FLlbdkhM7MWtFY3lEdN5xteGHV/+SS2flXzZGvn8KqbU8U+HF9/0h1etKcnKcnKT5XJ3bI0zv1U1rWvO9p3loYeQAAAAAAAAAAAb0K0oSUoScZLkcXZozE7dHqtrUnes7SmOhM43tDEK3/JFbPzL5ok0z+FlzpuKfDl+/wC0upVFJKUWpJ8jTumSYndc1tFo3huGQAAAAAAHL01p2lhl5T1p22Qi9r7dyNd8kVRNTrMeCOfOfJX+mNN1cQ/LlaN9kI81fVkS+SbdXPajV5M8+908nNNaMAAAAAAAAAAAAAAAAOlofTdXDvyJXjfbCXNf0ZspkmvRJ0+ryYJ92eXksDQunaWJXkvVnbbCT2rs3ol0yRZ0Om1mPPHLlPk6hsSwAAAw3ba9i6wdEPzBm9K9PDu75HU6F3N/aRsmfwqptXxPb3cX3/SF1Kjk3KTcm3tbd2yNM7qSZm07y1MMAAAB74LCTqzUKcXKT/bre5HqtZtO0NmPHbJaK1jm7ulso1KNPXjLjbLyko2ceuO9G2+Caxun5+G3x09qs7+aNmhWAAAAAAAAAAAA2p1HFqUW4tPY07NdhmJ2Zi01neE0y/m9O1PEOz5FU6H393aScefwsu9JxPf3cv3/AGmCd9q2okrlkABF8+46UKUacXbjJO9vVj0e9tGjPbaNvNV8VzTTHFI+JX5Dc8AAAAD6tG4CpXmqdNXb5X0RW9vceq1m07Q24cN8tvZqsvQehqeGhaO2b502tsvouonUpFYdPpdLTBXaOvjLpntJQ3NOV73rUI7eWVNdPXH6EbLh8aqbXcP33yYo9Y/SEkVRgADKV+RX7EZZ2Z1HufwYNpYcHufwYNpYMMAAAAAAWBkLHynSlTk78XJWv6suRe5pkzBbeNvJ0PCs03xzWfhSg3rQAgfCLU85Sjupt/F/0RdR1hQ8Xn36x8kSI6oAAAABLsqafw9ClqTjJVHPbKML613s29RIxZK1jaVxodZhxU9m0c07JS9APi0rpOnh4KdS+q5JeTG7u7/Q82vFY3lpz56Ya+1dWmYcZTrV5VKUdWLtyq2s+l26CFktE23hzOry0yZZtSNoc48IwBYHB/TXETdld1Xttt2JEvT9l0PCoj+KZ+aUaq3L4G9Z7Q1nTTTTSat0pbQTETGym6vOfefiVsuMt1lqGAAAAAS7g6qecqx304v4P+yRp+srfhE+/aPknZKXwBXOfp3xKW6lH922Q8/ac5xWd8+3yRo0q0AAAAHpQ50e8vER1eq9YXMiydmyBGOEH0ePto+EjRqOyrOK9zHqrsiOdAAFicH3o8vbS8IkvT9l0XCu5n1Sc3rNhgUxW50u8/ErZcZbrLQPIAAAAJLkCdsS1vpS/Zpm7B2lnwqds+3yWMTHRAFY52nfF1OqMF/iiFm7bmeJTvqJ+jgmpBAAAAB6UedHvLxEdWa9YXOiydmyBF+EL0ePto+EjRqOyrOK9zHqrsiOeAAFicHvo0vbS8IkvT9l0PCu5n1Sg3rNhgUvW50u8/ErZcZbrLQMAAAAA72SJ2xdPrjNf4s24e2ncNnbUR9VnE10wBVWbpXxdbvL+KIOXty5bXzvqLOOa0QAAAAG9DnR7y8RDNesLpRZOzZAi/CH6NH20fCRo1HZVnFe5j1V0RHPAACxeD30aXtpeESXp+y6HhXcz6pQb1mwwKWrc6XefiVsuMt1loGAAAAAdnKErYuj2y/izZi7cJegnbUVWoTnUgFTZpf+rr+0+SIGXty5XW9/f1co8IoAAAAN6HOj3l4iOrNesLqRZOzZA8MXg6dVatSEZxve0ldX3mJiJ6vGTHTJG1o3fJ9gYX7vT/Qjz/HXyaf6eD/EH2Bhfu9P9CH8dfI/p4P8QfYGF+70/wBCH8dfI/p4P8Q+vCYSnSWrThGEb3tFWV956iIjo3Y8dMcbVjZ7mXthgUrW50u8/ErZcZbrLQMAAAAA6uVX/q6Hf+TPeLtwlaLv6eq2Se6oAqTNHpdf2j+RAyduXKazv7+rlnhGAAAABvQ50e8vER1Zr1hdaLJ2bIAAAAAAAGGBSlfnS7z8Stnq4y3WWlwwAAAC4HUyv6XQ9ovBnvH24StF39PVbZPdUAVJmr0uv7T5IgZe3Lldb39/VyjwigAAAA3oc6PeXiIZr1hdiLJ2bIHhi8ZTpLWqTjCN7Xk7K+4xMxHV4vkrSN7Ts+T7fwv3il+tHn+Svm1f28H+4Pt/C/eKX60P5K+Z/bwf7g+38L94pfrQ/kr5n9vB/uH14TGU6q1qc4zje14u6vuPUTE9G2mSt43rO73MvbDApOvzpd5+JWz1cZbrLQMAAAAA6uVPS6HtPkz3i7cJWi7+nqtsnuqAKmzgrYyt3l+8UQcvbly2vj/os4xrRAAAAAelDnR7y8RHV6r1hdqLJ2TIEV4RvRo+2j4SNGfsqzivcx6q3IjngABZHBz6NL20vCJLwdl0PCu5n1So3rNhgUlX50u8/ErZ6uNt1l5h5AAAAB2snK+Mo96X7RZsxduEzQR/0VWwTnUAFV56jbGVOuMH/iiFm7bmeIxtqJ+jgGpBAAAABvQ50e8vER1eq9YXeiydkyBFOEf0aPto/wAZGjP2VZxXuY9VbkRzwAAsng59Gl7aXhEl4Oy6HhXcz6pUb1mwwKQr86XefiVs9XG26y0DyAAAADv5FjfGU+qM3/izbh7afw6N9RH1WoTXSgFZcIkLYq++lD9m18iHn7TneKRtn+iMGlXAAAAA3oc6PeXiI6s16wvBFk7JkCKcI/o0fbR/jI0Z+yrOK9zHqrYiOfAAFk8HHo0vbS/jEl4Oy6DhXcz6pWb1mwwKPr86XefiVs9XG26y0DAAAAAJPwdwvim91KX7tL5m7B2ljwuN830WaTHRAFecJlPztGW+m18Jf2RdR1hRcWj36z8kNI6pAAAABtRdpR7y8RDNesLwhUTSaaaa5U1tLJ2MTEw21lvXxDO6JcJFRf8AzwV1d1lsvtdoyNGefdVfFZj+KI+auCIoADqZawVKtXjTrTcINPkaTk+iN+i57x1i1tpSdJipkyxW87QtPQ+iqeGg6dLW1XJy8qV3d2XyJtaRWNodJgwUw19mr7j03AFe5wy7hsPS4yE5RqOatGU09e/LZW6CLlx1rG8KLXaPDip7VZ5oYR1SAAAACZcGdPztaW6nFfF/0SNP1lbcJj37T8lhkpegER4RtHynRhVir8XJ61vVlbb7ml8TRnrvG6r4pim2OLx4K3IigAAAAAA2VR+s/iwzvJxsvWf6mNz2pYlJvlbfawxuwAAJgT7KGbr2oYiW3khUfT1Te/rJOLL4WXeh1++2PJPpP7Tgkrhyswadp4WGtLypvmwT2yfyXWeL3isI2p1VMFd56+EKp0ppKpiKjqVJXb5F0RW6K6EQrWm07y5rNmvlt7VnyHlqAAAABZHBzo+UKM6slbjJLVv6sb7fe2yXgrtG6/4XimuObz4pcb1oAYlFNNNXTW1PkYJjdBcy5J5amFXW6X/h/IjZMPjVTarhvxYvt+kFqQcW1JOLTs01Zp9aIymmJidpahgAAAAAAAAAAAEq0NnarRpOnOHHWXkScrOPVLejdXNMRsssHEr46ezMb+SO4/G1K03UqScpP9upLoRqm0zO8oGTJbJb2rTzfOYeAAAA2pwcmoxTk27JJXb7EGYiZnaE6y1km1qmKXWqX/t/Ik48PjZc6ThvxZft+06jFJJJWS5EuRElcxGzIAAAA4un8t0cUrtalS2ypFbfzL/cjXfHFkTU6PHnjnynzVpprQVbCytUjeN9k47YS9/Q+pkS9Jr1c/qNLkwz70cvNzDwjgAAAAAAAAAAAAAAADp6E0FWxUrU42jfbOWyEff0vqR7pSbdEjT6XJmn3Y5eay9AZbo4VXitepbbUktv5V/tRLpjiroNNo8eCOXOfN2jYlgAAAAAAPOvRjOLjOKlFrapJNMxMbvNqxaNpjeEGzBkTlnhX/1Sf8JfJke+Dxqp9Twz4sX2/SD16MoScZxcJLlUk00R5jbqqLVms7TG0vMw8gAAAAAAAAAAA9KFGU5KMIucnyKKbbMxG/R6rWbTtEbynGX8ick8U/8Aqi/5y+SJFMHjZb6bhnxZft+05oUYwiowioxS2KKSSJERsua1isbRG0PQyyAAAAAAAAAAHO0voShiY2qwTfRJbJx7GeLUi3VozabHmja0fXxV7p3JdeheVPz9P8K8uK649PuI18Mx0Umo4dkx8684/KMNGlXAAAAAAAABICT6CyXXr2lU8xT/ABLy5Lqj0e83UwzPVY6fh2TJztyj8rC0RoWhho2pQSfTJ7Zy7WSq0ivRd4dNjwxtWPr4uiem8AAAAAAAAAAAAAAA4em8rYfE3bjxdT14WT/MuSRrvirZEz6LFm5zG0+cIDprKGIw95KPHU/WpptrvR5URr4rVUufQZcXPrHyR41IQAAAAJDoXKGIxFpOPE0/WqJ3fdjys20xWsm4NBly8+kfNP8AQmVsPhrNR4yp687N/lXJEk0xVqusGixYecRvPnLtmxLAAAAAAAAAAAAAAAAAAAA4emcrYbEXbhxc/Xp2T965Ga7Yq2RM+ixZecxtPnCD6XyRiKN3T8/D8Gya7Y/S5HthtHTmqM3DcuPnXnH5RziJ31dSWtu1Xf4GnaUD2Z322SPRGSMRWtKp5iH49s32R+purhtPXkn4eG5b87e7H5TnQ2VsNh7OMOMn69SzfuXIiRXFWq3waLFi5xG8+cu2bEsAAAAAAAAAAP/Z
